name: CD Deployment

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

env:
  # The folder on your OCI VM where the app actually runs
  PROD_DIR: /home/opc/avocado-ripening
  IMAGE_NAME: lepcodes/avocado-base

jobs:
  deploy:
    runs-on: [self-hosted, linux, ARM64]
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 1. Build Image
      - name: Build
        run: | 
          docker build -t ${{ env.IMAGE_NAME }}:latest .
          docker push ${{ env.IMAGE_NAME }}:latest

      # 2. Inject Secrets & Config
      - name: Update Config
        run: |
          mkdir -p ${{ env.PROD_DIR }}
          cp docker-compose.yml ${{ env.PROD_DIR }}/
          echo "${{ secrets.PROD_ENV_FILE }}" > ${{ env.PROD_DIR }}/.env

      # 3. Restart
      - name: Deploy
        run: |
          cd ${{ env.PROD_DIR }}
          docker compose up -d --remove-orphans
          docker image prune -f  