name: CD Deployment

on:
  workflow_run:
    workflows: ["CI Tests"]
    types:
      - completed

env:
  PROD_DIR: /home/ubuntu/avocado-ripening
  IMAGE_NAME: lepcodes/avocado-base

jobs:
  deploy:
    runs-on: [self-hosted, linux, ARM64]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & Push Image
        run: | 
          docker build -t ${{ env.IMAGE_NAME }}:latest .
          docker push ${{ env.IMAGE_NAME }}:latest

      - name: Update Config
        run: |
          mkdir -p ${{ env.PROD_DIR }}
          cp docker-compose.yaml ${{ env.PROD_DIR }}/
          echo "${{ secrets.PROD_ENV_FILE }}" > ${{ env.PROD_DIR }}/.env

      - name: Deploy to OCI
        run: |
          cd ${{ env.PROD_DIR }}
          docker compose up -d --remove-orphans
          docker image prune -f  